version: '3.8'
name: trendify
services:
  mysql:
    extends:
      file: ./mysql.yml
      service: mysql
  minio:
    extends:
      file: ./minio.yml
      service: minio
  trendify:
    container_name: trendify
    build:
      context: ../../../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
    - default

networks:
  default:
    name: trendify
