spring:
  application:
    name: trendify
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://172.0.1.75:3336/trendify
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect


# swagger
open:
  api:
    title: API Service
    version: v1.0.0
    description: API Doc for trendify application

# spring doc
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

# minio
integration:
  minio:
    access-key: OoeaO2H333E0EzGqayz4
    secret-key: 8ndtwupqla57VllS8AA5uqF2kEWBpzOhq51cBY1L
    url: http://localhost:9000
  vnpay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    returnUrl: http://localhost:5172
    tmnCode: 0QZQV8BP
    secretKey: JJSTFUGWAP8WBD9JM0MQTLJFP7XA66JI
    version: 2.1.0
    command: pay