spring:
  application:
    name: trendify
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: luutrieuvi2003@gmail.com
    password: bacrofozncoqsiqg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: @spring.profiles.active@

# swagger
open:
  api:
    title: API Service
    version: v1.0.0
    description: API Doc for trendify application

# spring doc
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs